import { addDays, subDays } from "date-fns";

const now = new Date();

export const demoAccountsSeed = {
  accounts: [
    {
      id: "acme-creative",
      name: "Acme Creative",
      industry: "Creative agency",
      owner: "Jordan Lee",
      segment: "Mid-Market" as const,
      createdAt: subDays(now, 400),
      updatedAt: now,
    },
    {
      id: "northstar-logistics",
      name: "Northstar Logistics",
      industry: "Logistics",
      owner: "Sam Rivera",
      segment: "SMB" as const,
      createdAt: subDays(now, 600),
      updatedAt: now,
    },
  ],
  opportunities: [
    {
      id: "opp-acme-001",
      accountId: "acme-creative",
      stage: "Negotiation",
      amount: 42000,
      probability: 75,
      closeDate: addDays(now, 28),
      daysInStage: 10,
      lastActivityAt: subDays(now, 3),
      owner: "Jordan Lee",
      sourceSystem: "salesforce" as const,
      sourceId: "006Acme000Negotiation",
      sourceUpdatedAt: subDays(now, 1),
    },
    {
      id: "opp-northstar-001",
      accountId: "northstar-logistics",
      stage: "Renewal",
      amount: 18000,
      probability: 55,
      closeDate: addDays(now, 22),
      daysInStage: 38,
      lastActivityAt: subDays(now, 24),
      owner: "Sam Rivera",
      sourceSystem: "salesforce" as const,
      sourceId: "006Northstar000Renewal",
      sourceUpdatedAt: subDays(now, 2),
    },
  ],
  calls: [
    {
      id: "call-acme-001",
      accountId: "acme-creative",
      occurredAt: subDays(now, 5),
      owner: "Jordan Lee",
      summary: "Expansion planning for contractor payroll and benefits rollout",
      themes: ["payroll automation", "benefits admin", "contractor onboarding"],
      excerpts: [
        "We are ready to add 12 contractors next quarter.",
        "Payroll automation saved our ops team hours each cycle.",
      ],
      sentiment: "positive" as const,
      sourceSystem: "gong" as const,
      sourceId: "gong:call_acme_001",
      sourceUpdatedAt: subDays(now, 5),
    },
    {
      id: "call-northstar-001",
      accountId: "northstar-logistics",
      occurredAt: subDays(now, 8),
      owner: "Sam Rivera",
      summary: "Renewal discussion surfaced payroll errors and support delays",
      themes: ["payroll errors", "slow support response", "renewal concern"],
      excerpts: [
        "We had three payroll errors this month and support took days to respond.",
        "I am frustrated that we are evaluating alternatives before renewal.",
      ],
      sentiment: "negative" as const,
      sourceSystem: "gong" as const,
      sourceId: "gong:call_northstar_001",
      sourceUpdatedAt: subDays(now, 8),
    },
  ],
  tickets: [
    {
      id: "ticket-acme-solved",
      accountId: "acme-creative",
      priority: "normal" as const,
      status: "solved" as const,
      createdAt: subDays(now, 50),
      summary: "Question about W-2 delivery timing",
      sourceSystem: "zendesk" as const,
      sourceId: "zendesk:acme_4412",
      sourceUpdatedAt: subDays(now, 45),
    },
    {
      id: "ticket-northstar-open",
      accountId: "northstar-logistics",
      priority: "high" as const,
      status: "open" as const,
      createdAt: subDays(now, 12),
      summary: "Payroll tax filing discrepancy for Q1",
      sourceSystem: "zendesk" as const,
      sourceId: "zendesk:northstar_8831",
      sourceUpdatedAt: subDays(now, 1),
    },
  ],
  healthSnapshots: [
    {
      id: "health-acme-001",
      accountId: "acme-creative",
      healthScore: 82,
      usageTrend: "up" as const,
      activeUsers: 68,
      lastLoginAt: subDays(now, 1),
      sourceSystem: "product_analytics" as const,
      sourceId: "pa:health_acme_001",
      sourceUpdatedAt: subDays(now, 1),
    },
    {
      id: "health-northstar-001",
      accountId: "northstar-logistics",
      healthScore: 41,
      usageTrend: "down" as const,
      activeUsers: 22,
      lastLoginAt: subDays(now, 19),
      sourceSystem: "product_analytics" as const,
      sourceId: "pa:health_northstar_001",
      sourceUpdatedAt: subDays(now, 2),
    },
  ],
};
