import { addDays, subDays } from "date-fns";

const now = new Date();

export const demoAccountsSeed = {
  accounts: [
    {
      id: "acme-creative",
      name: "Acme Creative",
      industry: "Creative agency",
      owner: "Jordan Lee",
      segment: "Mid-Market" as const,
      createdAt: subDays(now, 400),
      updatedAt: now,
    },
    {
      id: "northstar-logistics",
      name: "Northstar Logistics",
      industry: "Logistics",
      owner: "Sam Rivera",
      segment: "SMB" as const,
      createdAt: subDays(now, 600),
      updatedAt: now,
    },
    {
      id: "brightline-health",
      name: "Brightline Health Clinic",
      industry: "Healthcare",
      owner: "Dr. Priya Nair",
      segment: "Mid-Market" as const,
      createdAt: subDays(now, 320),
      updatedAt: now,
    },
    {
      id: "summit-legal",
      name: "Summit Legal Partners",
      industry: "Legal services",
      owner: "Alex Chen",
      segment: "Enterprise" as const,
      createdAt: subDays(now, 900),
      updatedAt: now,
    },
    {
      id: "harbor-foods",
      name: "Harbor Foods Co-op",
      industry: "Grocery / retail",
      owner: "Morgan Ellis",
      segment: "SMB" as const,
      createdAt: subDays(now, 120),
      updatedAt: now,
    },
  ],
  opportunities: [
    {
      id: "opp-acme-001",
      accountId: "acme-creative",
      stage: "Negotiation",
      amount: 42000,
      probability: 75,
      closeDate: addDays(now, 28),
      daysInStage: 10,
      lastActivityAt: subDays(now, 3),
      owner: "Jordan Lee",
      sourceSystem: "salesforce" as const,
      sourceId: "006Acme000Negotiation",
      sourceUpdatedAt: subDays(now, 1),
    },
    {
      id: "opp-northstar-001",
      accountId: "northstar-logistics",
      stage: "Renewal",
      amount: 18000,
      probability: 55,
      closeDate: addDays(now, 22),
      daysInStage: 38,
      lastActivityAt: subDays(now, 24),
      owner: "Sam Rivera",
      sourceSystem: "salesforce" as const,
      sourceId: "006Northstar000Renewal",
      sourceUpdatedAt: subDays(now, 2),
    },
    {
      id: "opp-brightline-001",
      accountId: "brightline-health",
      stage: "Renewal",
      amount: 55000,
      probability: 60,
      closeDate: addDays(now, 40),
      daysInStage: 22,
      lastActivityAt: subDays(now, 12),
      owner: "Dr. Priya Nair",
      sourceSystem: "salesforce" as const,
      sourceId: "006Brightline000Renewal",
      sourceUpdatedAt: subDays(now, 3),
    },
    {
      id: "opp-summit-001",
      accountId: "summit-legal",
      stage: "Renewal",
      amount: 120000,
      probability: 85,
      closeDate: addDays(now, 50),
      daysInStage: 12,
      lastActivityAt: subDays(now, 4),
      owner: "Alex Chen",
      sourceSystem: "salesforce" as const,
      sourceId: "006Summit000Renewal",
      sourceUpdatedAt: subDays(now, 1),
    },
    {
      id: "opp-harbor-001",
      accountId: "harbor-foods",
      stage: "Discovery",
      amount: 12000,
      probability: 40,
      closeDate: addDays(now, 60),
      daysInStage: 45,
      lastActivityAt: subDays(now, 26),
      owner: "Morgan Ellis",
      sourceSystem: "salesforce" as const,
      sourceId: "006Harbor000Discovery",
      sourceUpdatedAt: subDays(now, 5),
    },
  ],
  calls: [
    {
      id: "call-acme-001",
      accountId: "acme-creative",
      occurredAt: subDays(now, 5),
      owner: "Jordan Lee",
      summary: "Expansion planning for contractor payroll and benefits rollout",
      themes: ["payroll automation", "benefits admin", "contractor onboarding"],
      excerpts: [
        "We are ready to add 12 contractors next quarter.",
        "Payroll automation saved our ops team hours each cycle.",
      ],
      sentiment: "positive" as const,
      sourceSystem: "gong" as const,
      sourceId: "gong:call_acme_001",
      sourceUpdatedAt: subDays(now, 5),
    },
    {
      id: "call-northstar-001",
      accountId: "northstar-logistics",
      occurredAt: subDays(now, 8),
      owner: "Sam Rivera",
      summary: "Renewal discussion surfaced payroll errors and support delays",
      themes: ["payroll errors", "slow support response", "renewal concern"],
      excerpts: [
        "We had three payroll errors this month and support took days to respond.",
        "I am frustrated that we are evaluating alternatives before renewal.",
      ],
      sentiment: "negative" as const,
      sourceSystem: "gong" as const,
      sourceId: "gong:call_northstar_001",
      sourceUpdatedAt: subDays(now, 8),
    },
    {
      id: "call-brightline-001",
      accountId: "brightline-health",
      occurredAt: subDays(now, 10),
      owner: "Dr. Priya Nair",
      summary: "Renewal check-in with mixed feedback on reporting and onboarding",
      themes: ["benefits reporting", "onboarding gaps", "renewal planning"],
      excerpts: [
        "Reporting works but new hires still need hand-holding on benefits enrollment.",
        "We want to renew if onboarding improves before open enrollment.",
      ],
      sentiment: "neutral" as const,
      sourceSystem: "gong" as const,
      sourceId: "gong:call_brightline_001",
      sourceUpdatedAt: subDays(now, 10),
    },
    {
      id: "call-summit-001",
      accountId: "summit-legal",
      occurredAt: subDays(now, 6),
      owner: "Alex Chen",
      summary: "Enterprise renewal aligned on compliance and multi-state payroll",
      themes: ["compliance", "multi-state payroll", "partnership"],
      excerpts: [
        "Compliance reporting has been reliable across our three offices.",
        "We are planning to add a fourth office next year.",
      ],
      sentiment: "positive" as const,
      sourceSystem: "gong" as const,
      sourceId: "gong:call_summit_001",
      sourceUpdatedAt: subDays(now, 6),
    },
    {
      id: "call-harbor-001",
      accountId: "harbor-foods",
      occurredAt: subDays(now, 20),
      owner: "Morgan Ellis",
      summary: "Discovery call stalled after pricing and seasonal staffing questions",
      themes: ["pricing", "seasonal staff", "evaluation"],
      excerpts: [
        "We need clarity on seasonal worker pricing before moving forward.",
      ],
      sentiment: "neutral" as const,
      sourceSystem: "gong" as const,
      sourceId: "gong:call_harbor_001",
      sourceUpdatedAt: subDays(now, 20),
    },
  ],
  tickets: [
    {
      id: "ticket-acme-solved",
      accountId: "acme-creative",
      priority: "normal" as const,
      status: "solved" as const,
      createdAt: subDays(now, 50),
      summary: "Question about W-2 delivery timing",
      sourceSystem: "zendesk" as const,
      sourceId: "zendesk:acme_4412",
      sourceUpdatedAt: subDays(now, 45),
    },
    {
      id: "ticket-northstar-open",
      accountId: "northstar-logistics",
      priority: "high" as const,
      status: "open" as const,
      createdAt: subDays(now, 12),
      summary: "Payroll tax filing discrepancy for Q1",
      sourceSystem: "zendesk" as const,
      sourceId: "zendesk:northstar_8831",
      sourceUpdatedAt: subDays(now, 1),
    },
    {
      id: "ticket-brightline-open",
      accountId: "brightline-health",
      priority: "normal" as const,
      status: "open" as const,
      createdAt: subDays(now, 5),
      summary: "Benefits enrollment guide missing for part-time staff",
      sourceSystem: "zendesk" as const,
      sourceId: "zendesk:brightline_2201",
      sourceUpdatedAt: subDays(now, 2),
    },
    {
      id: "ticket-summit-solved",
      accountId: "summit-legal",
      priority: "low" as const,
      status: "solved" as const,
      createdAt: subDays(now, 30),
      summary: "SSO configuration question for HR admins",
      sourceSystem: "zendesk" as const,
      sourceId: "zendesk:summit_9920",
      sourceUpdatedAt: subDays(now, 28),
    },
    {
      id: "ticket-harbor-pending",
      accountId: "harbor-foods",
      priority: "normal" as const,
      status: "pending" as const,
      createdAt: subDays(now, 9),
      summary: "Demo environment access for finance reviewer",
      sourceSystem: "zendesk" as const,
      sourceId: "zendesk:harbor_1102",
      sourceUpdatedAt: subDays(now, 4),
    },
  ],
  healthSnapshots: [
    {
      id: "health-acme-001",
      accountId: "acme-creative",
      healthScore: 82,
      usageTrend: "up" as const,
      activeUsers: 68,
      lastLoginAt: subDays(now, 1),
      sourceSystem: "product_analytics" as const,
      sourceId: "pa:health_acme_001",
      sourceUpdatedAt: subDays(now, 1),
    },
    {
      id: "health-northstar-001",
      accountId: "northstar-logistics",
      healthScore: 41,
      usageTrend: "down" as const,
      activeUsers: 22,
      lastLoginAt: subDays(now, 19),
      sourceSystem: "product_analytics" as const,
      sourceId: "pa:health_northstar_001",
      sourceUpdatedAt: subDays(now, 2),
    },
    {
      id: "health-brightline-001",
      accountId: "brightline-health",
      healthScore: 58,
      usageTrend: "flat" as const,
      activeUsers: 44,
      lastLoginAt: subDays(now, 4),
      sourceSystem: "product_analytics" as const,
      sourceId: "pa:health_brightline_001",
      sourceUpdatedAt: subDays(now, 3),
    },
    {
      id: "health-summit-001",
      accountId: "summit-legal",
      healthScore: 76,
      usageTrend: "flat" as const,
      activeUsers: 210,
      lastLoginAt: subDays(now, 2),
      sourceSystem: "product_analytics" as const,
      sourceId: "pa:health_summit_001",
      sourceUpdatedAt: subDays(now, 1),
    },
    {
      id: "health-harbor-001",
      accountId: "harbor-foods",
      healthScore: 48,
      usageTrend: "flat" as const,
      activeUsers: 9,
      lastLoginAt: subDays(now, 14),
      sourceSystem: "product_analytics" as const,
      sourceId: "pa:health_harbor_001",
      sourceUpdatedAt: subDays(now, 5),
    },
  ],
};

export const DEMO_ACCOUNT_COUNT = demoAccountsSeed.accounts.length;
